### ISSUE TITLE
Event URL Format

### ISSUE THREAD

**Issue by DanielLearner** [jamespericles/Result-Bot#1]
The event URL is not guaranteed to follow the "tournament/alulu-${alulu?.value}/event/ultimate-singles" format. 

ex. https://www.start.gg/tournament/alulu-100-100-pot-bonus/event/ultimate-singles
ex2. https://www.start.gg/tournament/alulu-smash-70-1/event/ultimate-singles

I've found that the best way to get an guarantee getting the correct event is to first send a request to the api that gets all tournaments within 10 miles of Chicago bounded by a specific date range (some specific Tuesday), then search among those tournaments for one containing the string "alulu" in its name.

**Comment by jamespericles** [comment]
@DanielLearner [This commit](https://github.com/jamespericles/Result-Bot/commit/b9c9e059db46449414689d817c11dcbfaf710442) should resolve the bug you reported.

This commit adds a new `getTournamentByCoord` query which takes in an set of coordinates as a string as well as a radius to search around those coordinates. Currently both the coordinates and radius are hardcoded to be a mile around Alulu. 

The function (of the same name) that calls and executes this query loops over the array of tournaments given in the response and looks for a tournament with a name that includes 'Alulu' as well as the specific week count. With the correct node determined, we use the `name` property of the node to grab both the tournaments `id` as well as it's name, then returns both in the form of an object.

Thanks for pointing this bug out so long ago! With this resolved, the bot's ability to identify the correct tournament each week is no longer dependent on Bepis following the previously hardcoded URL format.
